### ISSUE TITLE
Https SNICallback problem

### ISSUE THREAD

**Issue by Andromeda1966** [metocean/redwire#8]
Using redwire.https(...., .....)  I got an error like the one below on nodejs server.
May you tell me what happen and how to solve the problem ?
I'm using Windows 7 + nodeJs + redwire.
Thanks in advance
Mauro

F:\testProxy\node_modules\redwire\src\certificate-store.js:51
          return callback(null, _this._secureContexts[hostname]);
                 ^
TypeError: undefined is not a function
    at Object.result.SNICallback [as onselect](F:testProxynode_modulesredwiresrccertificate-store.js:51:18)
    at SlabBuffer.use (tls.js:232:18)
    at CleartextStream.read [as _read](tls.js:450:29)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at callback (tls.js:839:20)
    at SecurePair.onclienthello (tls.js:846:5)
    at EncryptedStream.write [as _write](tls.js:357:31)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)

**Comment by Andromeda1966** [comment]
Solved.
Just upgrade Node !

**Comment by tcoats** [comment]
I'm glad things worked out. Please let me know if you have any additional issues or questions.
